import type { NextPage } from 'next';
import Head from 'next/head';
import MaxWidth from '../components/Atoms/MaxWidth';
import AboutUsPanel from '../components/Molecules/AboutUsPanel';
import ContactPanel from '../components/Molecules/ContactPanel';
import OurServicesPanel from '../components/Molecules/OurServicesPanel';
import HeroPanel from '../components/Templates/HeroPanel';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>DAGA Opakowania</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeroPanel />
            <MaxWidth>
                <AboutUsPanel />
                <OurServicesPanel />
            </MaxWidth>
            <ContactPanel />
        </div>
    );
};

export default Home;
