import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import HeroText from '../components/Atoms/HeroText';
import Header from '../components/Organisms/Header';

const Container = styled.div`
    max-width: 85rem;
    margin: 0 auto;
`;

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>DAGA Opakowania</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container>
                <Header />
                <HeroText />
            </Container>
        </div>
    );
};

export default Home;
